services:
  # Runtime application GroupBWT
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    command: composer --dev test
    volumes:
      - ./:/app
    networks:
      - backend

networks:
    backend: